### PR TITLE
More strict checking on CI

### PR DESCRIPTION
**Pull request by mrkkrp**

### CODE REVIEW

**Comment by NorfairKing** [comment]
I'm not convinced that it's sound to turn off optimisation for `dev`. What do you think?

**Comment by mrkkrp** [comment]
Why it is not sound?

**Comment by mrkkrp** [comment]
The reason it is turned off is that it makes builds faster, which is nice for CI.

**Comment by mrkkrp** [comment]
Why would optimization level influence anything that matters on CI? Only logic itself matters for tests, and other checks like `-Wall -Werror -Wcompat` have nothing to do with optimizations.

**Comment by joehillen** [comment]
I think NorfairKing is concerned about the fact that GHC's optimizer has had bugs in the past, but I think that's outside the scope of this library.

**Comment by NorfairKing** [comment]
@joehillen Correct

@mrkkrp I'm happy with this PR then. +1 from me.

**Comment by mrkkrp** [comment]
Let's have some faith in GHC, shall we? Bugs can be everywhere, after all :)

**Pull request merged**
