### PR TITLE
Marked the validity tests as parallelisable

### PR DESCRIPTION
**Pull request by NorfairKing**
This should help with #70

### CODE REVIEW

**Comment by sjakobi** [comment]
I can't see a difference in performance on either my machine or Travis. Can you?

**Comment by sjakobi** [comment]
> I can't see a difference in performance on either my machine or Travis. Can you?

Ah, I missed that we need to enable the `-N` RTS option. Can you add that?

**Comment by NorfairKing** [comment]
It certainly feels faster on my machine now.

**Comment by sjakobi** [comment]
> It certainly feels faster on my machine now.

On mine too! :+1:

**Pull request merged**
