### PR TITLE
try to run ci on ghc 9.0.1 as well

### PR DESCRIPTION
**Pull request by NorfairKing**

### CODE REVIEW

**Comment by NorfairKing** [comment]
https://github.com/actions/setup-haskell
It looks like GHC 9 is not supported by the github action to setup haskell yet.

**Comment by sjakobi** [comment]
https://github.com/actions/setup-haskell is apparently unmaintained now. It would be good to switch to https://github.com/haskell/actions, where I expect a release supporting GHC 9.0.1 soon. Alternatively you could use https://github.com/haskell-CI/haskell-ci, which already supports GHC 9.0.1 on `master`.

**Comment by NorfairKing** [comment]
@sjakobi I only _just got_ this working. You're welcome to try and convert it as long as we can keep it green.

**Comment by sjakobi** [comment]
I don't really want to get involved very deeply with this project. You could try copying `bytestring`'s setup which AFAIK is rather polished and even includes CI on FreeBSD: https://github.com/haskell/bytestring/blob/master/.github/workflows/ci.yml

I usually use `haskell-ci`, but it doesn't currently support Windows (https://github.com/haskell-CI/haskell-ci/issues/199) which seems rather essential for this project.

**Comment by NorfairKing** [comment]
@sjakobi Thanks for the links. I currently don't have the spare bandwidth to take this on. I would welcome anyone to take a shot at this. I may be able to help with reviews.

**Pull request closed without merging**
