### PR TITLE
Removed the need for type applications in validity-test

### LINKED ISSUE #80: Make validity-test compatible with GHC-7.10 and GHC-7.8
This would be nice for checking backwards compatibility and should allow us to remove the `validity` flag which would in turn simplify our CI configs.

This is currently blocked by our dependency on validity which requires `base >= 4.8` and on genvalidity-hspec which [(implicitly) requires `base >= 4.9`](https://github.com/NorfairKing/validity/issues/4).

It looks like validity can easily be made compatible with base-4.7, but genvalidity-hspec relies heavily on `TypeApplications`. We could probably make some ad-hoc helpers with hspec and QuickCheck to replace our use of genvalidity-hspec.

### PR DESCRIPTION
**Pull request by NorfairKing**
This should fix #80

### CODE REVIEW

**Comment by sjakobi** [comment]
Well, as I explained in #80, we need to make sure that our dependencies are compatible with GHC-7.8 and GHC-7.10 first.

So, if `genvalidity-hspec` can't be made compatible or replaced by a compatible replacement I guess we'll have to write a couple of test helpers of our own.

I'd also expect a fix to remove the "validity" flag.

**Comment by NorfairKing** [comment]
Ah, right. Not just the code.
I'm actually not in favor of inlining code from `genvalidity-hspec`, but I would like to hear other opinions on this matter.

**Comment by sjakobi** [comment]
> I'm actually not in favor of inlining code from genvalidity-hspec

It might actually be cleaner to rewrite validity-test to have a more classical property testsuite structure. We could even consider doing away with genvalidity and making the usual `Arbitrary` instance for a `ValidPath` newtype.

**Comment by NorfairKing** [comment]
> It might actually be cleaner to rewrite validity-test to have a more classical property testsuite structure. We could even consider doing away with genvalidity and making the usual Arbitrary instance for a ValidPath newtype.

You don't have to do away with `genvalidity`, only with `genvalidity-hspec`, and ONLY if you insist on sacrificing idiomatic code for backward compatibility.
You could still write `forAll genValid $ isValid . myFunc` without `genvalidit-hspec`

**Comment by sjakobi** [comment]
@NorfairKing Thanks for working on this! This PR is a bit hard to review now as the PR now includes various other changes. Would you mind separating your changes from those?

**Comment by NorfairKing** [comment]
Oh no! How did that happen!
I'll have to figure out how to chery-pick those two commits and put them on a new pull request. Closing this in the meantime.

**Pull request closed without merging**
