### PR TITLE
Remove module header

### PR DESCRIPTION
**Pull request by sjakobi**
@chrisdone Is this ok for you?

This info is just a duplicate of what's in the .cabal file and prone to get outdated.

### CODE REVIEW

**Comment by mrkkrp** [comment]
Why not have the header? I think it was me who added it. Why do you want to strip every piece of info that doesn't serve "raw" technical purpose? What's wrong in displaying a bit of info about author and maintainer at the top of module?

**Comment by sjakobi** [comment]
The fact that you forgot to update this header when you updated the copyright year in path.cabal just underlines my argument that this header is prone to get outdated and to incur additional maintenance overhead.

I also don't believe that anyone who looks at the haddocks for `Path` is particularly interested in the copyright info and who is the current maintainer.

> Why do you want to strip every piece of info that doesn't serve "raw" technical purpose?

Actually I want path to serve its users well and be easy to maintain.

Why do you like to add redundant information and other things that increase the maintenance overhead?

**Comment by mrkkrp** [comment]
I guess I just like when everything is fully specified, even if it's redundant. All that stuff doesn't make much difference anyway. And as I said, you can go ahead with this and merge.

**Comment by sjakobi** [comment]
Seems like we're counterbalancing each other nicely @mrkkrp! :smile:

**Pull request merged**
