### PR TITLE
Rename isParentOf and stripDir for clarity and consistency

### LINKED ISSUE #93: Rename isParentOf to isPrefixOf
As discussed in #90, `isParentOf` is a misnomer, leading to confusion at times. `isPrefixOf` conveys the meaning more clearly and effectively. We could rename the API and deprecate the old name.

### PR DESCRIPTION
**Pull request by harendra-kumar**
Fixes #93

### CODE REVIEW

**Comment by mrkkrp** [comment]
Can you quickly describe why the renaming is desirable? #93 sends to #90 for details, which has quite a few things in it. I feel like I forgot some context...

**Comment by harendra-kumar** [comment]
@mrkkrp strictly speaking,`parent` means the immediate parent of a child and not other ancestors. The semantics of `isParentOf` does not conform to that meaning, leading to confusion. For example, `isParentOf "/x" "/x/y/z"` is `True` but `parent "/x/y/z"` is not `"/x"`.  

Similarly, `parent "/"` is `"/"` but `isParentOf "/" "/"` is False - that's because `isParentOf` is a misnomer, if we rename it to `isProperPrefixOf` according to its correct semantics all these problems go away. As per [wikipedia](https://en.wikipedia.org/wiki/Substring) `A proper prefix of a string is not equal to the string itself`.

The renaming also fixes #33 because now the semantics of `parent` and `isProperPrefixOf` are clearly distinct.

**Comment by mrkkrp** [comment]
OK, please do the following:

* Add `@since 0.6.0` to doc strings of new names.
* Add a changelog entry (please note how the `CHANGELOG` is indented with tabs).
* In addition to "Deprecated" section in module's export list, add  a section called "Deprecated" in source code (like the existing ones "Parsers", "Operators", etc.) and put all the deprecated function synonyms there, so it's easy to navigate through the file.

**Comment by NorfairKing** [comment]
LGTM, it passes my sniff test.

**Pull request merged**
