### PR TITLE
Create Path.Posix and Path.Windows modules

### PR DESCRIPTION
**Pull request by sjakobi**
This is one half of the changes for #82 – making the testsuites platform-independent will be the other.

Simply importing `System.FilePath.{Posix,Windows}` instead of `System.FilePath` was nearly sufficient to make `Path.{Posix,Windows}` work independently of the current platform. The only real code change that was required was [a small change in `normalizeFilePath`](https://github.com/commercialhaskell/path/commit/309d85f9dd17bf33f904a3b6dd4cd0ed67e08cc3).

There's still room for improvement in the module docs, like e.g. in the compatibility warnings for the absolute path constructors ([example](https://github.com/commercialhaskell/path/blob/2504173a52c1128a4fe8f3cf75cf075fa8953b45/src/Path/Include.hs#L177)) but I feel like the current state is kind of good enough for a start.

### CODE REVIEW

**Comment by joehillen** [comment]
I'm a fan of this PR. I was introducing doctests and I couldn't find a good way to write and run doctest for Windows and Posix in the same file. This solves that problem.

To allay my earlier concerns, I did the following as a sanity check:

```
Prelude> import Path
Prelude Path> import qualified Path.Posix as P
Prelude Path P> import qualified Path.Windows as W
Prelude Path P W> :set -XQuasiQuotes
Prelude Path P W> [absfile|/etc/foo|]
"/etc/foo"
Prelude Path P W> fromAbsFile [absfile|/etc/foo|]
"/etc/foo"
Prelude Path P W> fromAbsFile [W.absfile|/etc/foo|]

<interactive>:14:13: error:
    • Exception when trying to run compile-time code:
        InvalidAbsFile "/etc/foo"
CallStack (from HasCallStack):
  error, called at /home/joe/src/haskell/path/src/Path/Include.hs:564:17 in main:Path.Windows
      Code: Language.Haskell.TH.Quote.quoteExp W.absfile "/etc/foo"
    • In the quasi-quotation: [W.absfile|/etc/foo|]
Prelude Path P W> W.fromAbsFile [absfile|/etc/foo|]

<interactive>:15:24: error:
    • Couldn't match type ‘Abs’
                     with ‘W.Abs’
      NB: ‘W.Abs’ is defined at
            /home/joe/src/haskell/path/src/Path/Include.hs:105:1-28
          ‘Abs’ is defined at
            /home/joe/src/haskell/path/src/Path/Include.hs:105:1-28
      Expected type: Path W.Abs W.File
        Actual type: Path Abs File
    • In the first argument of ‘W.fromAbsFile’, namely
        ‘(Path.Internal.Path "/etc/foo" :: Path Abs File)’
      In the expression:
        W.fromAbsFile (Path.Internal.Path "/etc/foo" :: Path Abs File)
      In an equation for ‘it’:
          it = W.fromAbsFile (Path.Internal.Path "/etc/foo" :: Path Abs File)
Prelude Path P W> P.fromAbsFile [absfile|/etc/foo|]
"/etc/foo"
Prelude Path P W> fromAbsFile [P.absfile|/etc/foo|]
"/etc/foo"
Prelude Path P W> P.fromAbsFile [W.absfile|C:\etc\foo|]

<interactive>:18:26: error:
    • Couldn't match type ‘W.Abs’
                     with ‘Abs’
      NB: ‘Abs’ is defined at
            /home/joe/src/haskell/path/src/Path/Include.hs:105:1-28
          ‘W.Abs’ is defined at
            /home/joe/src/haskell/path/src/Path/Include.hs:105:1-28
      Expected type: Path Abs File
        Actual type: Path W.Abs W.File
    • In the first argument of ‘fromAbsFile’, namely
        ‘(Path.Internal.Path "C:\\etc\\foo" :: Path W.Abs W.File)’
      In the expression:
        fromAbsFile
          (Path.Internal.Path "C:\\etc\\foo" :: Path W.Abs W.File)
      In an equation for ‘it’:
          it
            = fromAbsFile
                (Path.Internal.Path "C:\\etc\\foo" :: Path W.Abs W.File)
Prelude Path P W> W.fromAbsFile [W.absfile|C:\etc\foo|]
"C:\\etc\\foo"
Prelude Path P W> W.fromAbsFile [P.absfile|C:\etc\foo|]

<interactive>:20:15: error:
    • Exception when trying to run compile-time code:
        InvalidAbsFile "C:\\etc\\foo"
CallStack (from HasCallStack):
  error, called at /home/joe/src/haskell/path/src/Path/Include.hs:564:17 in main:Path.Posix
      Code: Language.Haskell.TH.Quote.quoteExp absfile "C:\\etc\\foo"
    • In the quasi-quotation: [P.absfile|C:\etc\foo|]
Prelude Path P W> P.fromAbsFile [P.absfile|C:\etc\foo|]

<interactive>:21:15: error:
    • Exception when trying to run compile-time code:
        InvalidAbsFile "C:\\etc\\foo"
CallStack (from HasCallStack):
  error, called at /home/joe/src/haskell/path/src/Path/Include.hs:564:17 in main:Path.Posix
      Code: Language.Haskell.TH.Quote.quoteExp absfile "C:\\etc\\foo"
    • In the quasi-quotation: [P.absfile|C:\etc\foo|]
```

Looks likes `Path.Windows.Abs` and `Path.Posix.Abs` are distinct types which is great.

One issue is that `InvalidAbsFile` is not descriptive enough in this case. Someone might look at the error and be confused because `[absfile|/etc/foo|]` looks valid but they're unintentionally using the Windows version of `absfile`. I wonder if there could be a different error for paths that fail to parse on one platform but pass for another. Perhaps `WrongPlatform`?

**Comment by sjakobi** [comment]
Thanks for testing my PR! :)

> Looks likes Path.Windows.Abs and Path.Posix.Abs are distinct types which is great.

Oh, I hadn't been aware of this consequence, but I agree that at least it doesn't seem to hurt.

> One issue is that InvalidAbsFile is not descriptive enough in this case. Someone might look at the error and be confused because [absfile|/etc/foo|] looks valid but they're unintentionally using the Windows version of absfile.

I agree that the error could be more descriptive but I'd prefer to wait for some actual user feedback to see if this issue comes up in practice. 

> I wonder if there could be a different error for paths that fail to parse on one platform but pass for another. Perhaps WrongPlatform?

This would require two parses and probably also make our code structure quite a bit more complex.

**Comment by NorfairKing** [comment]
> One issue is that InvalidAbsFile is not descriptive enough in this case. Someone might look at the error and be confused because [absfile|/etc/foo|] looks valid but they're unintentionally using the Windows version of absfile.

You could use [`validate`](https://hackage.haskell.org/package/validity-0.4.0.0/docs/Data-Validity.html#t:Validity) for that, but as @sjakobi says: first decide whether we need it.

**Comment by joehillen** [comment]
> I'd prefer to wait for some actual user feedback to see if this issue comes up in practice.

My intent is to improve user experience and save people some debugging time. I'm also imagining a scenario where someone develops on Linux and hardcodes everything for Unix paths (I've done this) and then shares it with someone on Windows. They will get compile time errors, but with a more descriptive error value the problem is more obvious. I doubt this package has a large enough user base for anyone to speak up, and it's bad user experience to wait until someone complains.

> This would require two parses

Yes, but only when throwing an error on a failed parse which should be rare, and it will typically happen at compile time.

> and probably also make our code structure quite a bit more complex.

It won't. Are you saying that you'd like me to do it instead?

**Comment by mrkkrp** [comment]
LGTM.

**Pull request merged**
