### PR TITLE
Allow '..' as part of larger path segments, clarify docs

### PR DESCRIPTION
**Pull request by sjakobi**
See https://github.com/commercialhaskell/path/issues/37#issuecomment-284566180.

### CODE REVIEW

**Comment by sjakobi** [comment]
Suggestions on how to improve the wording are very welcome!

**Comment by mrkkrp** [comment]
Who can go to AppVeyor and cancel all these queued builds? I can't.

**Comment by sjakobi** [comment]
> Who can go to AppVeyor and cancel all these queued builds?

Only @chrisdone AFAIK. Maybe we should move to an organizational account as described [here](https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization).

**Comment by sjakobi** [comment]
@mrkkrp: [I have configured](https://github.com/commercialhaskell/path/commit/b7807a22fb0dff01216b78173d7c6c30003302ec) AppVeyor to cache the stack root, so builds should be a bit quicker now.

**Comment by sjakobi** [comment]
I'd like to have #78 merged first and then rebase this one to get the docs and tests changes.

**Comment by harendra-kumar** [comment]
@sjakobi I have some conflicting doc changes in #34 . If that's reasonable we can keep only the newly added tests from this one.

**Comment by sjakobi** [comment]
> If that's reasonable we can keep only the newly added tests from this one.

Sure.

**Pull request closed without merging**
