### PR TITLE
A sum type uniting absolute and base paths, for parsing

### PR DESCRIPTION
**Pull request by mstksg**
Thank you for the great library! :)

I've had some situations where I've had to parse a filepath as "either absolute or relative", and have had to branch on one situation or the other.  I've pulled together some of the common logic as a type in case you might be interested.  The main type is:

```haskell
data SomeBase t = Abs (Path Abs t)
                | Rel (Path Rel t)
```

which is mostly useful for parsing:

```haskell
parseSomeDir :: MonadException m => FilePath -> m (SomeBase Dir)
parseSomeFile :: MonadException m => FilePath -> m (SomeBase File)
```

Users can parse a `FilePath` representing a `Dir` or a `File`, and then branch on whether the path was abs or relative.

If this doesn't really fit into the library as it is, feel free to close :)

### CODE REVIEW

**Comment by NorfairKing** [comment]
I've needed this in the past, so I wouldn't mind.
I'm not much fussed to bikeshed the name, but I'd definitely like to hear the opinion of the other contributors.

**Comment by chrisdone** [comment]
I like this, +1 from me.

**Comment by NorfairKing** [comment]
@mstksg LGTM then. We need a rebase though.

**Comment by mstksg** [comment]
Rebase completed :)  Note that the stack resolver in the stack.yaml won't compile as-is, since it is tied to a GHC older than the base bounds.

**Comment by NorfairKing** [comment]
@mstksg  then I guess you're blocked on #147

**Comment by jecaro** [comment]
Just wanted to let you know that I'd love to see PR merged into master. Also thanks for such an awesome library.

**Comment by chrisdone** [comment]
The merge conflict seemed trivial so I resolved it. The compile might still fail, but that's fine. This PR seems to have stalled but not for any reason, so waking it up again. Thanks @jecaro

**Comment by chrisdone** [comment]
Tests passed, merged! Thanks @mstksg. Sorry about the year-long delay.

**Comment by mstksg** [comment]
no worries, happy i was able to contribute :D

**Pull request merged**
